### ISSUE TITLE
Unable to create Bucket: cannot find bucket error

### ISSUE THREAD

**Issue by angelhvargas** [crossplane-contrib/provider-influxdb#7]
### What happened?

I'm trying to create the following Bucket (external resource)
```
apiVersion: influxdb.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: example-bucket2
spec:
  forProvider:
    description: test-description
    orgID: *******4e54da6
    retentionRules:
    - everySeconds: 0
      type: expire
  providerConfigRef:
    name: default
```

The bucket doesn't get created.

```
$ > kubectl describe Bucket example-bucket


Name:         example-bucket2
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-name: example-bucket2
API Version:  influxdb.crossplane.io/v1alpha1
Kind:         Bucket
Metadata:
  Creation Timestamp:  2022-01-06T18:50:00Z
  Generation:          1
  Managed Fields:
    API Version:  influxdb.crossplane.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:deletionPolicy:
        f:forProvider:
          .:
          f:description:
          f:orgID:
          f:retentionRules:
        f:providerConfigRef:
          .:
          f:name:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-01-06T18:50:00Z
    API Version:  influxdb.crossplane.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:crossplane.io/external-name:
      f:status:
        .:
        f:atProvider:
          .:
          f:links:
        f:conditions:
    Manager:         crossplane-influxdb-provider
    Operation:       Update
    Time:            2022-01-06T18:50:01Z
  Resource Version:  328220
  UID:               9d4acba6-e5fc-46ee-9d10-44423123123
Spec:
  Deletion Policy:  Delete
  For Provider:
    Description:  test-description
    Org ID:       YOUR_ORG_ID****
    Retention Rules:
      Every Seconds:  0
      Type:           expire
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
    Links:
  Conditions:
    Last Transition Time:  2022-01-06T18:50:01Z
    Message:               observe failed: cannot find bucket: not found: bucket "example-bucket2" not found
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                         Age              From                                   Message
  ----     ------                         ----             ----                                   -------
  Warning  CannotObserveExternalResource  4s (x4 over 5s)  managed/bucket.influxdb.crossplane.io  cannot find bucket: not found: bucket "example-bucket2" not found
```

### How can we reproduce it?

- AKS cluster Kubernetes v1.20.13.
- Using a InfluxDB Cloud 2.0 account, Azure:

Install the provider:

```
kubectl crossplane install provider crossplane/provider-influxdb:v0.1.0
```

Apply the following:

```
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: influxdb-token
type: Opaque
stringData:
  authToken: YOUR_INFLUXDBCLOUD_TOKEN_ID==
---
apiVersion: influxdb.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  endpoint: https://eastus-1.azure.cloud2.influxdata.com
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: influxdb-token
      key: authToken
---
apiVersion: influxdb.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: example-bucket2
spec:
  forProvider:
    description: test-description
    orgID: YOUR_TEST_ORG
    retentionRules:
    - everySeconds: 0
      type: expire
  providerConfigRef:
    name: default
```

### What environment did it happen in?
Crossplane version: upbound/crossplane:v1.5.1-up.1

Provider InfluxDB Cloud version: v0.1.0

Azure AKS

Kubernetes 1.20.13
